cspell.config.yaml
packages/moonshine-web/netlify.toml
packages/stage-ui/src/components/Scenes/VRM.vue
packages/stage-ui/src/components/VRM/Model.vue
packages/stage-ui/src/composables/vrm/animation.ts
packages/stage-web/netlify.toml
packages/stage-web/src/components/Layouts/InteractiveArea.vue
packages/whisper-webgpu/netlify.toml

* Animate (synthetic) idle eye saccades with a simple implementation (Please feel free to tune these parameters)
* Clean up VRM and before-render callbacks upon unmounting (to avoid duplicating VRMs on hot reload and crashing the browser)
<details>
<summary>Duplicate VRMs look like this (Viewer discretion is advised)</summary>
</details>
* Fix missing component imports (warnings)

feat(stage-ui): animate idle eye saccades on VRMs

---

packages/stage-ui/src/components/Live2D/Viewer.vue
packages/stage-ui/src/composables/live2d/animation.ts
packages/stage-ui/src/composables/live2d/index.ts
packages/stage-ui/src/composables/vrm/animation.ts
packages/stage-ui/src/utils/eye-motions.ts
packages/stage-ui/src/utils/index.ts

* Animate idle eye saccades and focus (head) movements on Live2D models
*For Live2D models: Eyeball movements will be turned off in all motions of the idle motion group to avoid conflicts*

feat(stage-ui): animate idle eye and focus movements on Live2D models

---

apps/stage-web/src/components/Layouts/MobileInteractiveArea.vue
apps/stage-web/src/pages/index.vue
packages/stage-ui/src/components/Live2D/Model.vue
packages/stage-ui/src/components/Scenes/Live2D.vue
packages/stage-ui/src/components/Scenes/VRM.vue
packages/stage-ui/src/components/VRM/Model.vue
packages/stage-ui/src/components/Widgets/Stage.vue

Now it will pause rendering when settings drawer open, optimize performance for mobile.
Maybe we should not organize props like this, but now I cannot find other ways.

perf(stage-web): pause render when settings open

---

apps/stage-web/src/components/Menu/IconItem.vue
apps/stage-web/uno.config.ts

This pull request adds dotted-pattern backgrounds to buttons on the Settings page and adds some reusable UnoCSS rules.
|Normal|Hovered|
|:-:|:-:|
|<img width="874" alt="Screenshot 2025-03-08 at 0 18 14" src="https://github.com/user-attachments/assets/ee01c374-38e3-4b07-abfb-7a20c3a45c9c" />|<img width="874" alt="Screenshot 2025-03-08 at 0 18 23" src="https://github.com/user-attachments/assets/cc0b9350-70d6-4059-84ff-94fb2a25a899" />|

feat(stage-web): add dotted background to settings buttons

---

apps/stage-web/src/pages/settings/index.vue

> This PR is optional as I'm not sure if it was intended
Adds a back button for the Settings root page b/c I found myself getting lost until I realized the HeaderLink is clickable:
|Before|After|
|:-|:-|
|<img width="827" alt="Screenshot 2025-03-08 at 3 38 30" src="https://github.com/user-attachments/assets/34215a58-7584-43c7-a2c8-0d722a854c17" />|<img width="827" alt="Screenshot 2025-03-08 at 3 38 12" src="https://github.com/user-attachments/assets/f05ef3e4-bf77-4f50-bc57-37bf5916b73e" />|

fix(stage-web): add back button to settings root

---

packages/ui-transitions/src/components/ArrowTransition.vue
packages/ui-transitions/src/components/BubbleWaveOutTransition.vue
packages/ui-transitions/src/components/FantasyFallTransition.vue
packages/ui-transitions/src/components/MultipleBlocksRevealTransition.vue
packages/ui-transitions/src/components/RectanglesRotateTransition.vue
packages/ui-transitions/src/components/SlideTransition.vue
packages/ui-transitions/src/components/SlopeSlideTransition.vue

instead of `absolute` as the web page might be scrolled down
reproduce:
https://github.com/user-attachments/assets/11d2ebcd-509e-40f2-ba94-0eb13d6ced4f

fix(ui-transitions): the outermost div should be fixed

---

cspell.config.yaml
packages/stage-ui/README.md
packages/stage-ui/build.config.ts
packages/stage-ui/env.d.ts
packages/stage-ui/histoire.config.ts
packages/stage-ui/package.json
packages/stage-ui/src/components/Menu/IconItem.story.vue
packages/stage-ui/src/components/Menu/IconItem.vue
packages/stage-ui/src/components/Menu/IconStatusItem.story.vue
packages/stage-ui/stories/Colors.story.vue
packages/stage-ui/stories/ThemeColorsHueControl.vue
packages/stage-ui/stories/main.css
packages/stage-ui/stories/setup.ts
packages/stage-ui/stories/themes.css
packages/stage-ui/stories/transitions.css
packages/stage-ui/tsconfig.json
packages/stage-ui/uno.config.ts
packages/stage-ui/vite.config.ts
pnpm-lock.yaml

This pull request serves as the first PR to integrate Histoire into `@proj-airi/stage-ui`
Some idea: Maybe we should consider making UnoCSS config reusable between these stage- projects, as the config at stage-web and stage-tamagotchi are almost identical 
1. If a story is bound to a specific component, it can be placed beside the component in the `src` folder. e.g., `MyComponent.story.vue`
2. If a story is not bound to a specific component, then it should be placed in the `stories` folder. e.g., `MyStory.story.vue`

feat(stage-ui): integrate histoire storyboard

---

Cargo.lock
apps/stage-tamagotchi/src-tauri/Cargo.toml
apps/stage-tamagotchi/src-tauri/src/commands.rs
apps/stage-tamagotchi/src-tauri/src/lib.rs

Fix #146
Also disabled the reload keyboard shortcut.
Caused by: https://github.com/tauri-apps/wry/issues/583

fix(tamagotchi): process stuck when create settings window on Windows

---

apps/stage-tamagotchi/src/pages/settings/providers/google-generative-ai.vue
apps/stage-web/src/pages/settings/providers/google-generative-ai.vue

Google Gemini API key doesn't start with `sk-`
https://github.com/moeru-ai/airi/issues/176

update API key placeholder to 'GEMINI_API_KEY'

---

apps/stage-tamagotchi/locales/en.yml
apps/stage-tamagotchi/locales/zh-CN.yml
apps/stage-web/locales/en.yml
apps/stage-web/locales/zh-CN.yml

This PR adds missing i18n entries for the "MCP Server" module in both English and Chinese (en.yml, zh-CN.yml):
- Adds `title` and `description` fields under the modules section
- Ensures the settings/modules UI displays the MCP Server module correctly
- Follows the naming and description style of existing modules
Impact:
- UI only, no breaking changes
- Other locale files are not affected
Please help review, thanks!

fix(i18n): add MCP Server module title and description to en/zh-CN locales

---

apps/stage-tamagotchi/src/layouts/settings.vue

- Unified the background color of the settings content area and PageHeader in dark mode to match the card  style for a more consistent visual experience.
- Fixed the issue where the PageHeader background color did not match the content/card area in dark theme.
- Before
- After
- This change only affects the settings page in the desktop app (stage-tamagotchi) and does not impact other pages or features.

fix(settings): unify dark theme background color for content area and header

---

.gemini/styleguide.md

This pull request adds the initial style guide for Gemini Code Assist. In the style guide, "Suggestions" were added as the very first instruction.
https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github#style-guide

chore(gemini): add the initial style guide for suggestions

---

uno.config.ts

fix(ci): ETIMEDOUT for ipv4 & ENETUNREACH for ipv6 when fetching fonts from `@unocss/preset-web-fonts`

---

apps/stage-tamagotchi/src/pages/settings/airi-card/index.vue
apps/stage-tamagotchi/src/pages/settings/modules/consciousness.vue
apps/stage-tamagotchi/src/pages/settings/modules/hearing.vue
apps/stage-tamagotchi/src/pages/settings/modules/speech.vue
apps/stage-web/src/pages/settings/airi-card/index.vue
apps/stage-web/src/pages/settings/modules/consciousness.vue
apps/stage-web/src/pages/settings/modules/hearing.vue
apps/stage-web/src/pages/settings/modules/speech.vue
packages/i18n/src/locales/en/settings.yaml
packages/stage-ui/src/components/Menu/RadioCardManySelect.vue
packages/stage-ui/src/components/Menu/VoiceCardManySelect.vue
packages/stage-ui/src/components/Misc/Alert.vue
packages/stage-ui/src/components/Misc/ErrorContainer.vue
packages/stage-ui/src/components/Misc/index.ts

refactor(stage-ui): `<Alert> <ErrorContainer>`

---

apps/stage-web/package.json
apps/stage-web/vite.config.ts
pnpm-lock.yaml

fix: pwa service worker registering

---

apps/playground-prompt-engineering/uno.config.ts
apps/realtime-audio/uno.config.ts
apps/stage-tamagotchi/uno.config.ts
apps/stage-web/uno.config.ts
uno.config.ts

debug(workspace): unocss fonts split shared testing

---

cspell.config.yaml
packages/stage-ui/package.json
packages/stage-ui/src/components/Scenarios/Providers/SpeechPlayground.vue
packages/stage-ui/src/components/Scenarios/Providers/SpeechStreamingPlayground.vue
packages/stage-ui/src/composables/queues.ts
packages/stage-ui/src/utils/tts.ts
pnpm-lock.yaml

* Adds a generator function `chunkTTSInput` in `packages/stage-ui/src/utils/tts.ts` to pre-process text into chunks before streaming them to the speech provider, to reduce the first-chunk wait time while preferring to generate speech with complete sentences. (Please allow me to book a slot in our DevLog to explain this.)
* Adds a simple playground to test the TTS chunking and streaming. Available inside the Voice Playground:

feat(stage-ui): better tts input chunking

---

packages/stage-ui/src/components/Widgets/PoppinText/PoppinText.web.vue

Let's replace the grapheme cluster splitter with the one from `clustr`

refactor(stage-ui): replace grapheme cluster reader from clustr

---

packages/stage-ui/src/components/Scenarios/Settings/ModelSettings/VRM.vue
packages/stage-ui/src/components/Scenes/VRM.vue
packages/stage-ui/src/components/Scenes/VRM/Model.vue
packages/stage-ui/src/components/Scenes/VRM/OrbitControls.vue

This is a possible fix. Try to enforce the camera position and target setting to be after the creation of Model and OrbitControls, such that these objects are not undefined.
- Reset camera position and target of OrbitControls needs the information of the VRM model (Centre position & model size, etc), which will not be calculated after the loading of the Model.
If this can't fix it, then an issue to track it is needed.
None

fix(stage-ui): In the prod, the camera was not being set correct pos and target

---

packages/stage-ui/src/components/Scenes/Live2D/Model.vue
packages/stage-ui/src/components/Scenes/VRM/Model.vue

Cleaning up Live2D and VRM models on HMR as well. Although the `onUnmounted` hook should have been called on HMR, sometimes it doesn't (in our case). This may help prevent the models from being loaded and added to the scene multiple times without proper cleanup.

fix(stage-ui): clean up models on HMR

---

packages/i18n/src/locales/en/settings.yaml
packages/i18n/src/locales/zh-Hans/settings.yaml
packages/stage-ui/src/components/Scenarios/Settings/ModelSettings/VRM.vue
packages/stage-ui/src/components/Scenes/VRM.vue
packages/stage-ui/src/components/Scenes/VRM/Model.vue
packages/stage-ui/src/stores/vrm.ts

This is an update for the last PR regarding the look at functionality for VRM models. User can now switch between 3 types of eye tracking modes: looking at mouse, looking at camera, and looking forward
[https://github.com/moeru-ai/airi/issues/318](https://github.com/moeru-ai/airi/issues/318)
None.

feat(stage-ui): LookAt 3 functions: looking at camera; looking at mouse; looking forward (tracking disabled)

---

apps/stage-web/src/components/Widgets/ChatHistory.vue

Due to the incorrect v-if conditions, all the historical AIRI's chat will be shown as 3-dot loading. Now this condition has been fixed. All AIRI's chat history is visible now.
None
None

fix(stage-web): Now only the last AIRI's chat will be showing as 3 dots loading status.

---

packages/stage-ui/src/composables/queues.ts
packages/stage-ui/src/utils/stream.ts
packages/stage-ui/src/utils/tts.ts

As a follow-up to our [discussion](https://github.com/moeru-ai/airi/pull/330/files/7d973d5f9d38cbaa1c2bdd8c7d2c8745d7dea7b3#r2240268721), introducing a helper function `chunkToTTSQueue` to provide the reader to the TTS chunking processor and then pipe the chunks to the TTS queue, and a helper function `createControllableStream` to create externally controllable `ReadableStream`s at ease.

feat(stage-ui): introduce helpers for stream and tts chunking

---

packages/stage-ui/src/stores/chat.ts
packages/stage-ui/src/utils/tts.ts

When reading the codes for the TTS generation, I realised that the current code will not keep the decimal itself in the tts input text:
```
if (flush || hard || soft) {
switch (value) {
case '.':
case ',': {
if (previousValue !== undefined && /\d/.test(previousValue)) {
const next = await iterator.next()
if (!next.done && next.value && /\d/.test(next.value)) {
// This dot could be a decimal point, so we skip it
previousValue = next.value
current = next
continue
}
}
}
}
```
Moreover, the value assignment to previousValue and current is also a little bit confusing, so I re-write it.
Some other commented code is for debugging. I also realised that AIRI will stop talking if the last chunk ends with "a normal character (not hard not soft not flush) and a flush (\u200B)". The last sentence will …

fix(stage-ui) TTS decimals are now retained, AIRI will no longer say "25" if it's "2.5"

---

packages/stage-ui/src/stores/chat.ts

Enqueuing 2x TTS_FLUSH_INSTRUCTION tokens to ensure there is always one left in the grapheme cluster reader and the other in the TTS chunking reader. This should flush the leftover chunk inside the TTS pipeline, especially when there are no hard punctuations in the last chunk.
Closes #341

fix(stage-ui): enqueue 2x TTS_FLUSH_INSTRUCTION tokens

---

packages/stage-ui/src/components/Layouts/Tabs.vue
packages/stage-ui/src/components/Layouts/index.ts
packages/stage-ui/src/components/Scenarios/Settings/ModelSettings/VRM.vue
packages/stage-ui/src/components/Scenes/VRM.vue
packages/stage-ui/src/components/Scenes/VRM/Environment.vue
packages/stage-ui/src/components/Scenes/VRM/Model.vue
packages/stage-ui/src/stores/vrm.ts

Hemisphere light is a rough model to describe the environmental lighting. On the model setting page, users can now switch between the hemisphere light environment and the sky box environment. The setting sub-panel will be changed, and the related components in the VRM scene will also be mounted/dismounted.
Using hemisphere light:
Using sky box:
Will add an issue as a TODO for the sky box-related environment lighting.
1. I also made some changes to the VRM model loading code... but I don't think it's the final and perfect solution. I just added some code to let the model reset to the default when the URL input is empty.
2. The next 2 steps are the following:
* Enable the user to adjust the background blurriness and intensitive on the settings page
* Write the environment lighting for the …

feat(stage-ui): Switch between hemisphere light and sky box

---

packages/stage-ui/src/stores/display-models.ts

Fix Cant Pick newly uploaded model on tamagotchi due to inability to maintain model data list
This pull request modifies the `getDisplayModel` function in the `display-models` store to fetch data directly from `localforage` instead of relying on the in-memory `displayModels` ref.
When running the application in multiple windows, the `displayModels` ref can become stale. If a model is added in one window via `addDisplayModel`, other windows are not aware of this change, leading to data inconsistencies. When `getDisplayModel` is called in another window, it accesses the outdated in-memory cache and fails to find the newly added model.
The `getDisplayModel` function has been updated to bypass the in-memory cache and query `localforage` directly. This ensures that it always retrieves the most …

fix(stage-ui): Ensure display model data consistency across windows

---

packages/server-runtime/src/index.ts

Index.ts
- Cache AUTH_TOKEN at startup instead of re-reading from process.env
- Pre-stringify frequent responses (authenticated / not authenticated) to reduce JSON.stringify calls
- Cache broadcast payloads to avoid repeated serialization per recipient
- Add peersByModule index for O(1) lookups in ui:configure instead of linear scan
- Mutate existing peer objects with Object.assign instead of recreating
- Add safe JSON.parse guard to handle malformed incoming messages
- Ensure module peers are unregistered on disconnect. idk i think it will be better
This PR improves the performance and scalability of WebSocket peer handling and event routing in `index.ts.`
It does not change the protocol or behavior — only optimizes the implementation for lower overhead and faster lookups.
Reviewers may …

optimize WebSocket handling in packages/server-runtime/src/index.ts

---

apps/stage-tamagotchi/src/bindings/tauri-plugins/window-pass-through-on-hover.ts
apps/stage-tamagotchi/src/composables/tauri.ts
apps/stage-tamagotchi/src/pages/index.vue

This commit fixes an issue where the application window was blank on its first launch and corrects the data structure for the `tauri://move` event to handle window repositioning correctly.
1.  **Blank Window on First Load:** On initial startup, the main window was rendered with zero opacity, making it appear blank until the first mouse interaction.
2.  **Incorrect Event Payload:** The `tauri://move` event listener was attempting to access window coordinates from a nested `payload` object (`event.payload.payload.x`) that did not exist, causing errors when moving the window.
1.  A new `isFirstTime` reactive flag was added. The UI's opacity is now prevented from being set to zero on the initial render, ensuring content is visible immediately. The transparency logic is now only applied after …

fix(stage-tamagotchi): fix first time initialization blank and an overlook

---

packages/server-runtime/src/index.ts

**Fixed an issue** where `p.index` was always undefined because `event.data.index` was never assigned, causing multiple modules with the same name but different indexes to overwrite each other in `peersByModule.`
**Changes:**
- Correctly assign `event.data.index` to `p.index.`
- Unregister the existing module peer before re-announcing.
- Ensure `peersByModule` remains consistent on disconnect.
**Description:**
This update prevents module peers from being overwritten when they share the same name but use different indexes. It improves peer lifecycle management by properly assigning indexes, unregistering before re-announcing, and ensuring cleanup on disconnect.

Fix: prevent module peer overwrite on re-announce

---

apps/stage-web/src/components/Widgets/ChatHistory.vue
packages/stage-ui/src/composables/llmmarkerParser.ts
packages/stage-ui/src/stores/chat.ts

* Move back to the FSM-style opening/closing tags scanner in `useLlmmarkerParser` to emit literals ASAP, otherwise they are only emitted when a complete tag is parsed
* Time complexity should be linear
* Pass all tests in `llmmarkerParser.test.ts`
* Fix: Emit special tokens with the surrounding `<|` and `|>` to keep the behavior untouched
* Fix: Do not emit a literal if it's part of an incomplete special tag
* Show the streaming message in the web chat history

fix(stage-ui,stage-web): emit literals asap and show streaming messages

---

packages/stage-ui/src/components/Scenarios/Settings/ModelSettings/VRM.vue
packages/stage-ui/src/components/Scenes/VRM.vue
packages/stage-ui/src/components/Scenes/VRM/Model.vue
packages/stage-ui/src/components/Scenes/VRM/SkyBoxEnvironment.vue

I enhanced the shader injection:
1. IBL diffusion: Diffuse irradiance implemented. The SH coefficients are calculated in the skybox component and then fed into the Model.vue
2. IBL reflection: Using mipmap to make the reflection less PBR.
[https://github.com/moeru-ai/airi/issues/358](https://github.com/moeru-ai/airi/issues/358)
An important step towards a better NPR shader!
TODO:
* Refactoring needed to seperate the shader-related code 
* We can use the color in hdri texture to decide the tinting in the shadow/highlight areas
* What's a better way to do specular reflection? We don't need it on the skin material.
* Rim light?
* More NPR visual effect? such as 「目の透け」
A little bit diverted from the "AI" part into the CG part...hhh

feat(stage-ui/VRM) Better skybox IBL: irrSH diffusion & Specular reflection

---

apps/stage-web/src/components/Layouts/MobileInteractiveArea.vue

This PR is to Enable Enter key submission for desktop users in MobileInteractiveArea component.
Desktop users in `MobileInteractiveArea.vue` component couldn't submit with Enter key. Mobile users continue to get new lines with Enter (no change)
none
none

fix(stage-web): support on pc submit with enter

---

packages/stage-ui/src/components/Scenes/VRM.vue
packages/stage-ui/src/components/Scenes/VRM/Model.vue
packages/stage-ui/src/stores/vrm.ts

After [https://github.com/moeru-ai/airi/pull/554](https://github.com/moeru-ai/airi/pull/554), I realised that although the directional light can be adjusted in the setting page, it will still be reset due to Three.js's api mechanism...
The light instance's target must be correctly added to the scene so that the target change can be applied at the start when the light component was mounted...
none
No idea why the API was designed like this...

fix(stage-ui/VRM) Directional light setting results can be really applied and persist

---

apps/stage-web/src/pages/settings/modules/speech.vue
packages/i18n/src/locales/en/settings.yaml
packages/i18n/src/locales/zh-Hans/settings.yaml
packages/stage-ui/src/components/Menu/VoiceCard.vue
packages/stage-ui/src/components/Menu/VoiceCardManySelect.vue
packages/stage-ui/src/stores/providers.ts

This PR fixes speech module is unable to test voice with openai and alibaba.
- add `compatibleModels` for `VoiceInfo`
- add more friendly information when no supported voices of selected speech model.
- add more friendly information when no preview voice samples.
- fix OpenAI speech models are not shown.
- fix unable to test voice
Add `compatibleModels` field because voices are not only decided by provider but also player's selected model. For example, 龙婉 is only supported by cosyvoice-v1. Previous renderer logic is using provider to select all voices and then render. It's fail to test voice when player select a voice which is not supported by his/her selected model. <br/>
Add `listModels` for `providerMetadata['openai-audio-speech']` reason is openai-audio-speech has `capabilities` field …

fix(speech): unable to test voice with openai and cosyvoice-v2 in speech module

---

.github/workflows/update-nix-assets-hash.yaml
.github/workflows/update-nix-pnpm-deps-hash.yaml

Fixes #604
> This means that there can be at most one running and one pending job in a concurrency group at any time. When a concurrent job or workflow is queued, if another job or workflow using the same concurrency group in the repository is in progress, the queued job or workflow will be pending. Any existing pending job or workflow in the same concurrency group, if it exists, will be canceled and the new queued job or workflow will take its place.
We only have two update actions, so should be fine. With more than two we would have to rely on other methods

fix(nix): run hash update actions sequentially

---

packages/stage-ui/src/stores/providers.ts

On the settings/providers/novita-ai page, it showed "Configuration validation success" and on the settings/modules/consciousness, it showed the novita-ai is a available provider even without api key
This PR add chat_completions as one way to justify its validation. 
fixed #614 
It still need to be tested since I don't want to buy some token to verify if it still works well with available api key

fix: update validation of novita-ai so it will be invalid without api key
