moeru-ai/airi

README.md
README.zh-CN.md

change airi.ayaka.io to airi.moeru.ai

docs: update links in README.md

---

package.json

Ref: https://github.com/pnpm/pnpm/issues/9032#issuecomment-2633440395

fix(monorepo): missing scripts stub before typecheck, pnpm approve-builds fix

---

packages/drizzle-duckdb-wasm/package.json
packages/drizzle-duckdb-wasm/playground/src/App.vue
pnpm-lock.yaml

chore(drizzle-duckdb-wasm): improved button color, added support for switching theme

---

pnpm-workspace.yaml

chore(workspace): use yaml anchors for catalog version

---

.vscode/settings.json
apps/stage-web/locales/en.yml
apps/stage-web/locales/zh-CN.yml
apps/stage-web/package.json
apps/stage-web/src/components/Widgets/Live2DSettings.vue
apps/stage-web/src/components/Widgets/MobileSettings.vue
packages/stage-ui/src/components/Live2D/Model.vue
packages/stage-ui/src/components/Scenes/Live2D.vue
packages/stage-ui/src/components/Widgets/Stage.vue
packages/stage-ui/src/stores/settings.ts
packages/stage-ui/src/utils/live2d-zip-loader.ts
pnpm-lock.yaml

Now it can load and save other live2D model, but blink and motions broken, I will fix it soon.
Can I use pinia to let data cross `apps/stage-web/src/components/Widgets/Live2DSettings.vue` and `packages/stage-ui/src/components/Live2D/Model.vue`? Or should I use props and emit to do this?

feat(stage-web): load and save live2d model

---

docs/src/content/docs/blog/DevLog-2025.03.05.md

docs: fix a code error in DevLog-2025.03.05

---

apps/stage-web/src/components/Layouts/AnimatedBackground.vue

Fixes several issues found with the wave animation:
* Aligns animation speed to pixels/sec to better ensure consistency under different framerates
* Corrects the width of the SVG element to fix the choppy animation under some circumstances
<video src="https://github.com/user-attachments/assets/e15581fe-aace-4343-bea7-d6e79c9314e9">

fix(stage-web): wave animation

---

apps/stage-tamagotchi/src/renderer/src/components/ChatHistory.vue
apps/stage-tamagotchi/src/renderer/src/components/InteractiveArea.vue
apps/stage-tamagotchi/src/renderer/src/pages/index.vue
apps/stage-tamagotchi/src/renderer/src/pages/settings.vue
apps/stage-web/src/App.vue
apps/stage-web/src/components/Backgrounds/Cross.vue
apps/stage-web/src/components/Layouts/AnimatedBackground.vue
apps/stage-web/src/components/Layouts/InteractiveArea.vue
apps/stage-web/src/components/Layouts/MobileInteractiveArea.vue
apps/stage-web/src/components/Menu/IconItem.vue
apps/stage-web/src/components/Widgets/ChatHistory.vue
apps/stage-web/src/components/Widgets/Live2DSettings.vue
apps/stage-web/src/components/Widgets/MobileChatHistory.vue
apps/stage-web/src/pages/index.vue
apps/stage-web/src/pages/settings/index.vue
apps/stage-web/src/pages/settings/models/index.vue
apps/stage-web/src/pages/settings/modules/index.vue
apps/stage-web/src/pages/settings/themes/index.vue
apps/stage-web/src/styles/themes.css
apps/stage-web/uno.config.ts
packages/stage-ui/src/components/Widgets/Stage.vue
packages/stage-ui/src/stores/settings.ts
packages/ui-transitions/src/components/StageTransitionGroup.vue

https://github.com/user-attachments/assets/49f3ca32-d006-4a47-9381-4b81a0068154

feat(stage): custom primary colors

---

cspell.config.yaml
package.json
pnpm-lock.yaml

https://github.com/SukkaW/nolyfill
```bash
pnpm nolyfill # check
pnpm nolyfill install # update
```

perf: use nolyfill to reduce install size

---

apps/stage-web/src/components/Layouts/InteractiveArea.vue
apps/stage-web/uno.config.ts

but keep the color difference, <del>this is done by adding `brightness-105 hue-rotate-240 saturate-125` color translation filters</del>
now it is done by creating complementary colors

chore(stage-web): make the buttons follow the color scheme

---

services/twitter-services/package.json
services/twitter-services/src/adapters/mcp-adapter.ts
services/twitter-services/src/core/auth-service.ts
services/twitter-services/src/core/twitter-service.ts
services/twitter-services/src/main.ts
services/twitter-services/src/parsers/tweet-parser.ts

```json
{
"contents": [
{
"uri": "twitter://user/luoling8192",
"text": "Profile for @luoling8192 (RainbowBird)\n数字游民 / OIer / 全栈开发者 /  DevOps"
}
]
}
```

feat(twitter-services): timeline & profile support

---

cspell.config.yaml
docs/astro.config.ts
docs/package.json
docs/src/components/starlight/Head.astro
docs/src/env.d.ts
docs/src/pages/og/[...slug].ts
pnpm-lock.yaml

feat(docs): add og-image

---

packages/drizzle-duckdb-wasm/playground/src/components/Memory/DecayModelSettings.vue
packages/drizzle-duckdb-wasm/playground/src/components/Memory/RecordDetail.vue

Misc fixes for the memory-decay playground

fix(drizzle-duckdb-wasm): misc details in memory playground

---

apps/stage-tamagotchi/index.html

fix(stage-tamagotchi): CSP blocked many requests

---

apps/playground-prompt-engineering/index.html
apps/playground-prompt-engineering/package.json
apps/playground-prompt-engineering/src/App.vue
apps/playground-prompt-engineering/src/assets/main.css
apps/playground-prompt-engineering/src/components/ChatSimulator.vue
apps/playground-prompt-engineering/src/components/ControlPanel.vue
apps/playground-prompt-engineering/src/components/HeaderComponent.vue
apps/playground-prompt-engineering/src/components/Notification.vue
apps/playground-prompt-engineering/src/components/PromptPreview.vue
apps/playground-prompt-engineering/src/composables/useCharacterPrompt.ts
apps/playground-prompt-engineering/src/composables/useChatSimulator.ts
apps/playground-prompt-engineering/src/main.ts
apps/playground-prompt-engineering/tsconfig.json
apps/playground-prompt-engineering/uno.config.ts
apps/playground-prompt-engineering/vite.config.ts
pnpm-lock.yaml

feat: prompt engineering playground

---

README.ja-JP.md
README.md

I created Japanese translated README.

docs: add Japanese README file

---

packages/ui/README.md

Add README.md for `ui` package.
#159

docs(ui): add README

---

packages/ui-transitions/README.md

Add README.md for `ui-transitions` package.
#160

docs(ui-transitions): add README

---

packages/ui-loading-screens/README.md

Add README.md for `ui-loading-screens` package.
#161

docs(ui-loading-screens): add README

---

packages/server-shared/README.md

Add README.md for `server-shared` package.
#163

docs(server-shared): add README

---

packages/ui/README.md

docs(ui): add usage in README

---

packages/ui-transitions/package.json
pnpm-lock.yaml

This reverts commit dafe4d6f48570481329d7830716d3da7a5b26fd4.

Revert "fix(ui-transitions): build (#177)"

---

README.ja-JP.md
README.md
README.zh-CN.md

docs(readme): update n3p6 link

---

Cargo.lock
apps/stage-tamagotchi/src-tauri/Cargo.toml
apps/stage-tamagotchi/src-tauri/src/lib.rs
apps/stage-tamagotchi/src/pages/index.vue
apps/stage-tamagotchi/src/stores/window-controls.ts
apps/stage-tamagotchi/src/types/window-controls.ts

As demo
https://github.com/user-attachments/assets/9f51c99c-f7ab-4653-9022-62ac001a1d9b

feat(stage-tamagotchi): allowing click through and fade away when hovering (currently macOS only)

---

.vscode/settings.json
apps/stage-tamagotchi/src-tauri/src/app_click_through/mod.rs
apps/stage-tamagotchi/src-tauri/src/app_click_through/native_macos.rs
apps/stage-tamagotchi/src-tauri/src/app_click_through/native_windows.rs
apps/stage-tamagotchi/src-tauri/src/app_click_through/state.rs
apps/stage-tamagotchi/src-tauri/src/app_click_through/types.rs
apps/stage-tamagotchi/src-tauri/src/commands.rs
apps/stage-tamagotchi/src-tauri/src/lib.rs
apps/stage-tamagotchi/src/pages/index.vue
apps/stage-tamagotchi/src/pages/settings/models/index.vue
apps/stage-web/src/pages/index.vue
apps/stage-web/src/pages/settings/models/index.vue
packages/stage-ui/src/components/Live2D/Model.vue
packages/stage-ui/src/components/Scenes/Live2D.vue
packages/stage-ui/src/components/Widgets/Stage.vue

https://github.com/user-attachments/assets/cf7b0602-8b08-4386-b92f-f02d43b1cb69

feat(stage-tamagotchi): live2d model look at mouse position

---

apps/stage-tamagotchi/locales/en.yml
apps/stage-tamagotchi/locales/zh-CN.yml
apps/stage-tamagotchi/src-tauri/capabilities/default.json
apps/stage-tamagotchi/src/App.vue
apps/stage-tamagotchi/src/pages/settings/appearance/general.vue
packages/stage-ui/src/stores/settings.ts

https://github.com/user-attachments/assets/85322a28-d0a0-458f-ba4c-28fe9da7d8b7

feat(stage-tamagotchi): allow visible on all workspace

---

.github/workflows/ci.yml
apps/stage-web/netlify.toml
package.json
packages/stage-ui/package.json
packages/stage-ui/vite.config.ts
packages/ui-loading-screens/netlify.toml
packages/ui-loading-screens/package.json
packages/ui-loading-screens/vite.config.ts
packages/ui-transitions/netlify.toml
packages/ui-transitions/package.json
pnpm-lock.yaml

chore(ci): improve build test CI

---

README.md
apps/stage-tamagotchi/src/pages/settings/providers/player2.vue
apps/stage-web/src/pages/settings/modules/speech.vue
apps/stage-web/src/pages/settings/providers/player2-speech.vue
apps/stage-web/src/pages/settings/providers/player2.vue
docs/README.ja-JP.md
docs/README.zh-CN.md
packages/i18n/src/locales/en/settings.yaml
packages/i18n/src/locales/zh-Hans/settings.yaml
packages/stage-ui/src/stores/modules/consciousness.ts
packages/stage-ui/src/stores/modules/speech.ts
packages/stage-ui/src/stores/providers.ts
pnpm-lock.yaml
pnpm-workspace.yaml

Adds player2 speech support to airi (made a new branch, cleaned up code a bit)
had to update xsai version as well b.c. of the buffer thing

chore(stage-web): Player2 speech

---

apps/stage-tamagotchi/src/components/Widgets/Live2DSettings.vue
apps/stage-tamagotchi/src/pages/index.vue
apps/stage-tamagotchi/src/pages/settings/models/index.vue
apps/stage-web/src/components/Widgets/Live2DSettings.vue
apps/stage-web/src/pages/index.vue
apps/stage-web/src/pages/settings/models/index.vue
packages/i18n/src/locales/en/settings.yaml
packages/i18n/src/locales/zh-Hans/settings.yaml
packages/stage-ui/src/components/Scenes/Live2D.vue
packages/stage-ui/src/components/Scenes/Live2D/Model.vue
packages/stage-ui/src/components/Scenes/Stage.vue
packages/stage-ui/src/stores/settings.ts
packages/stage-ui/tsconfig.json

Close #265 
https://github.com/user-attachments/assets/24e6222f-7352-40d4-a1b5-152e14547103

feat(stage): change scale and position of live2d model

---

README.md

Fix minor typos in README (grammar unchanged)
This PR corrects a few spelling mistakes in the README file. No grammar or structural edits were made.
N/A
Grammar and syntax improvements are still needed and can be addressed in a future PR.

docs(README): typos

---

packages/stage-ui/src/components/Scenarios/Providers/SpeechPlayground.vue
packages/ui/src/components/Form/Field/FieldSelect.vue
packages/ui/src/components/Form/Select/Select.vue

This is helpful when failing to fetch data (ack moeru-ai/unspeech#31)

feat: show placeholder when lists has no data

---

apps/stage-tamagotchi/src/components/InteractiveArea.vue
apps/stage-web/src/components/Layouts/InteractiveArea.vue
apps/stage-web/src/components/Layouts/MobileInteractiveArea.vue
packages/stage-ui/package.json
packages/stage-ui/src/stores/chat.ts
packages/stage-ui/src/stores/llm.test.ts
packages/stage-ui/src/stores/llm.ts
packages/stage-ui/vite.config.ts
packages/stage-ui/vitest.config.ts
pnpm-lock.yaml
pnpm-workspace.yaml

fix(stage-*): passed `tools` without check & discovery for provider

---

package.nix

fix(nix): bump version, remove cuda support

---

packages/stage-ui/src/stores/chat.ts
packages/stage-ui/src/stores/llm.ts
pnpm-lock.yaml
pnpm-workspace.yaml

chore(deps): bump xsai, std

---

cspell.config.yaml
docs/.vitepress/components/BlogPosts.vue
docs/content/en/blog/DevLog-2025.06.08/index.md
docs/content/en/blog/DevLog-2025.07.18/index.md
docs/content/en/blog/DevLog-2025.08.01/index.md
docs/content/en/blog/DreamLog-0x1/index.md
docs/content/zh-Hans/blog/DevLog-2025.07.18/index.md
docs/content/zh-Hans/blog/DevLog-2025.08.01/index.md
docs/content/zh-Hans/blog/DreamLog-0x1/index.md

feat(docs): support to read excerpt from frontmatter

---

packages/ui/src/components/Animations/TransitionVertical.vue

修复 TransitionVertical 的打断动画异常
异常大多发生于使用 v-show 切换模式下，总结来说有以下两个问题：
- 由于使用 `getComputedStyle` 获取原先元素该有的高度，但是由于有动画正在运行，返回的值其实是动画中的值。导致在触发进入动画时的目标高度错误
- 将当前动画中的高度值设为新动画的初始值，导致在退出动画时从中间状态从头播放了一个新动画，时长仍然是原先动画该有的时长，但是初始值是运动到一半的高度
原先状态
https://github.com/user-attachments/assets/9bff7ce3-87f4-484b-97df-33a7ab917386
应用本 Patch 之后状态
https://github.com/user-attachments/assets/95cf1b58-665a-48f0-984d-d565f13dbccf
另外，要使退出动画的打断工作，似乎必须使用 v-show 模式。
因为如果使用 v-if 的话，打断退出动画的一瞬间 Vue 会销毁原先的 div 并创建一个新的再触发开始动画，并且文档上说 `@leave-cancelled` 钩子不可用。
这似乎是 Vue Transition 组件的特性，无法在我们的组件中修复

fix(ui): TransitionVertical Interrupt animation

---

.gemini/config.yaml
.github/workflows/ci.yml

ci: skip crowdin

---

apps/stage-tamagotchi/src/pages/settings/providers/lm-studio.vue
apps/stage-web/src/pages/settings/providers/lm-studio.vue
packages/i18n/src/locales/en/settings.yaml
packages/i18n/src/locales/es/settings.yaml
packages/i18n/src/locales/zh-Hans/settings.yaml
packages/stage-ui/src/stores/providers.ts

Added LM Studio as a provider
https://github.com/moeru-ai/airi/issues/155

feat: LM Studio Provider

---

apps/stage-tamagotchi/src/pages/settings/modules/speech.vue
apps/stage-tamagotchi/src/pages/settings/providers/openai-compatible-audio-speech.vue
apps/stage-tamagotchi/src/pages/settings/providers/openai-compatible-audio-transcription.vue
apps/stage-tamagotchi/src/pages/settings/providers/openai-compatible.vue
packages/i18n/src/locales/en/settings.yaml
packages/i18n/src/locales/es/settings.yaml
packages/i18n/src/locales/zh-Hans/settings.yaml
packages/stage-ui/src/components/Scenarios/Providers/OpenAICompatibleSpeechPlayground.vue
packages/stage-ui/src/stores/onboarding.ts
packages/stage-ui/src/stores/providers.ts

- Directly address #401 #388
This change adds a flexible, generic provider that can be configured with a custom baseUrl and apiKey. While this might seem redundant next to the existing OpenAI provider, its purpose is to make future requests like "Can you add Provider A, B, or C?" obsolete. Since many current and emerging AI services follow the OpenAI API specification, this single provider empowers users to connect to almost any of them without waiting for a dedicated integration. This approach removes user doubt about whether their preferred service is compatible and provides a unified, future-proof way to integrate with a growing ecosystem of tools. The provider is designed for chat, TTS, and STT tasks and has been successfully tested with external services like Groq's playtts-ai. …

feat: Add generic OpenAI-compatible provider for chat and audio

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
package.nix

docs: add instruction on running the nix package, chore(nix): update hash

---

apps/stage-web/src/pages/settings/providers/ollama.vue
packages/i18n/src/locales/en/settings.yaml
packages/i18n/src/locales/zh-Hans/settings.yaml
packages/stage-ui/src/components/Misc/Alert.vue

- ollama config page now has validator loading animation

feat: ollama setting pages now has validating animation

---

docs/content/en/docs/overview/index.md

The phrase "Web is much minimum for accessing it anywhere" contains "minimum" used incorrectly as an adjective where "minimal" should be used.
NA
NA

typo corrected

---

docs/.vitepress/components/MotionToggle.vue
docs/content/zh-Hans/blog/DevLog-2025.08.26/components/nms-iou.vue
docs/content/zh-Hans/blog/DevLog-2025.08.26/index.md

feat(devlog): add nms example for devlog-2026-08-26

---

crates/tauri-plugin-ipc-audio-transcription-ort/src/models/whisper/whisper.rs

Improves Whisper pipeline stability and safety by fixing decoder input handling, 
adding safer conversions, and making error messages clearer. Refactors 
download helper for consistency and validates encoder outputs to avoid 
silent failures.
Ensure the correctness of changes in the decoding loop and the security of the encoder
decoder.

fix(whisper): improve robustness and fix decoder prefix handling

---

apps/stage-web/src/components/Layouts/InteractiveArea.vue
apps/stage-web/src/components/Layouts/MobileInteractiveArea.vue
packages/stage-ui/src/stores/chat.ts

feat(chat): store message in localstorage, add a button for cleanup

---

packages/stage-ui/src/stores/providers.ts

This pr fix the wrong alibaba speech model name in stage-ui/src/stores to ensure test voice function in speech module works well.
- fix alibaba tts model name from `cozyvoice` to `cosyvoice`
#567

fix(stage-ui): reolve speech module cannot test voice using alibaba cosyvoice-v1

---

packages/stage-ui/src/stores/display-models.ts

fix(stage-ui): padding model preview to correct aspect ratio

---

packages/i18n/src/locales/ru/tamagotchi/settings.yaml

убрал фразу на английском на русском переводе и вы можете это сделать в коде

chore(i18n): fix russian transition

---

apps/stage-web/Dockerfile

Fix the `stage-web` Dockerfile to allow it to build properly and publish the image using CI.
N/A.
N/A.

fix(stage-web): Dockerfile failed to build

---

apps/stage-tamagotchi/src/main/index.ts
apps/stage-tamagotchi/src/renderer/App.vue
apps/stage-tamagotchi/src/shared/eventa.ts

feat(tray): electron tray
